# Generated by Django 4.0.4 on 2022-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar/avatar_deault.jpg', upload_to='images/avatar/', verbose_name='Аватар'),
        ),
    ]
