# Generated by Django 4.0.4 on 2022-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar/avatar_default.jpg', upload_to='images/avatar/', verbose_name='Аватар'),
        ),
    ]
